version: '3'
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    environment:
      - discovery.type=single-node
      - logger.level=WARN
      - xpack.security.enabled=false
    networks:
      - app_network
  flask-api:
    container_name: flask
    image: omril/postgres-semantic-search:latest
    environment:
      - FLASK_DEBUG=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PG_DB_NAME=${PG_DB_NAME}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_HOST=${PG_HOST}
      - PG_TABLE_NAME=${PG_TABLE_NAME}
      - PG_FIELDS=${PG_FIELDS}
      - PG_ID_FIELD=${PG_ID_FIELD}
    ports:
      - 5000:5000
    depends_on:
      - elasticsearch
    networks:
      - app_network

networks:
  app_network:
    driver: bridge